from resources.mappings import *
from resources.actions import *
from resources.routes import *
from resources.auth import *
from resources.system import *
from resources.diagnostic_report import *
from resources.observation import *
from resources.patient import *
from resources.practitioner import *
from resources.procedure import *
from resources.condition import *
from resources.family_history import *
from resources.medication import *
from resources.medication_statement import *
from resources.immunization import *
from resources.organization import *
